codevise/pageflow-progress-navigation-bar

- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default.css.scss
- app/views/pageflow/progress_navigation_bar/widget/_bar_top.html.erb
Some themes do not have an overview.
> Add theme option to hide overview button

- app/assets/javascript/pageflow/progress_navigation_bar/widget.js
Do not display controls when moving towards bar. Gets in the way when using hotspot page type.
> Remove display magic

- app/views/pageflow/progress_navigation_bar/widget/_bar_top.html.erb
- app/views/pageflow/progress_navigation_bar/widget/_home_button.html.erb
- app/views/pageflow/progress_navigation_bar/widget/_page.html.erb
- config/locales/new/public.removed.yml
See also: https://github.com/codevise/pageflow/issues/406
> Extract publicly visible i18n strings from locale

- app/assets/javascript/pageflow/progress_navigation_bar/widget.js
- app/assets/stylesheets/pageflow/progress_navigation_bar.css.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/animations.scss
Smooth transitions for page dots on storyline change.
> Animate storylines

- app/views/pageflow/progress_navigation_bar/widget/_bar_top.html.erb
Reduce duplication and enable custom share url feature.
> Use share links partials from Pageflow gem

- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default.css.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/buttons.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/credits.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/menu_boxes.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/share_box.scss
Add SCSS variables while keeping previous values as defaults.
> Make link and menu box colors configurable

- app/assets/stylesheets/pageflow/progress_navigation_bar.css.scss
> Prevent hover effect for deactivated top button

- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/icons/sprite.scss
Had to be switched on the vertical bar.
> Fix volume up/down icons

- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/icons/icon_font.scss
* Volume up and down were switched in vertical version
* Position in horizontal variant was not correct
> Fix icon font volume icons

- app/assets/stylesheets/pageflow/progress_navigation_bar.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/typography.scss
Extract typographic settings from base css.
> Make typography configurable in theme

- app/assets/stylesheets/pageflow/progress_navigation_bar.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/horizontal.scss
- pageflow-progress-navigation-bar.gemspec
* Use logical direction mixins
* Ensure slider works by settings direction to ltr
> Right to left layout support

- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default.scss
- Added the option to granular style each chapter indicator
- removed unused variables
> Chapter Indicator color options

- app/assets/javascript/pageflow/progress_navigation_bar/widget.js
- app/assets/stylesheets/pageflow/progress_navigation_bar.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/horizontal.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/vertical.scss
Fade in mobile navigation bar at the top during page transitions on mobile.
Use horizontal variant on phone also if horizontal slideshow navigation feature is enabled.
REDMINE-15849
> Add horizontal mobile variant

- app/assets/javascript/pageflow/progress_navigation_bar/widget.js
Decouple from feature flag.
REDMINE-15849
> Use pageflow.navigationDirection

- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/icons/icon_font.scss
Can be used to set colors.
REDMINE-15986
> Make widget-icon-font-options apply to buttons

- app/assets/stylesheets/pageflow/progress_navigation_bar.scss
- app/views/pageflow/progress_navigation_bar/widget/_page.html.erb
Make page links friendlier for screen readers and search engines.
REDMINE-16513
> Include text in navigation bar links

- app/assets/stylesheets/pageflow/progress_navigation_bar.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/typography.scss
- app/views/pageflow/progress_navigation_bar/widget/_page.html.erb
- pageflow-progress-navigation-bar.gemspec
> Remove redundant chapter headers from document outline

- app/assets/javascript/pageflow/progress_navigation_bar/widget.js
- app/assets/stylesheets/pageflow/progress_navigation_bar.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default.scss
- app/views/pageflow/progress_navigation_bar/_widget.html.erb
- app/views/pageflow/progress_navigation_bar/widget/_page.html.erb
> Hide chapter in single-chapter storylines

- app/views/pageflow/progress_navigation_bar/widget/_page.html.erb
- pageflow-progress-navigation-bar.gemspec
> Adjust page partial to new page_helper-syntax

- app/assets/stylesheets/pageflow/progress_navigation_bar.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default.scss
- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/indicator.scss
> Add theme option to use custom indicator image

- pageflow-progress-navigation-bar.gemspec
> Add support for Pageflow 16

- app/assets/stylesheets/pageflow/progress_navigation_bar/themes/default/menu_boxes.scss
> Add theme option to hide chapter number in page detail boxes

- lib/pageflow-progress-navigation-bar.rb
- lib/pageflow/progress_navigation_bar/engine.rb
- pageflow-progress-navigation-bar.gemspec
> Rails 6 suppport
